### ISSUE TITLE
curl_multi_exec is causing high throughput

### ISSUE THREAD

**Issue by jjin-gfm** [algolia/algoliasearch-client-php#184]
![algolia-multi-exec-throughput](https://cloud.githubusercontent.com/assets/15371751/20811098/3353ab1c-b7c1-11e6-9489-43f948133cc3.PNG)

Every few weeks, we see this happening on our servers. The only usage of curl_multi_exec is in the algolia SDK. Currently investigating some more on reasons why this might be happening.

We are on PHP 5.6.26

Code in question:

        $running = null;
        do {
            $mrc = curl_multi_exec($mhandle, $running);
        } while ($mrc == CURLM_CALL_MULTI_PERFORM);

        while ($running && $mrc == CURLM_OK) {
            if (curl_multi_select($mhandle, 0.1) == -1) {
                usleep(100);
            }
            do {
                $mrc = curl_multi_exec($mhandle, $running);
            } while ($mrc == CURLM_CALL_MULTI_PERFORM);
        }

**Comment by rayrutjes** [comment]
We are going to investigate this issue. Thanks for reporting in.

**Comment by rayrutjes** [comment]
@jjin-gfm thanks for your patience,

The mentioned code looks like the recommend approach to use cURL.

The throughput you are experiencing is linked to the fact that we need to loop and call `curl_multi_exec` at a high frequency to reduce the time between the moment where the response is ready and the moment we fetch the response in PHP.

Apart from the actual fact that you notice this high throughput, is it a problem for your servers?
If so could you give us more context so that we could eventually come up with an optimization suggestion?

**Comment by rayrutjes** [comment]
@jjin-gfm please note that we are working on a way to share the knowledge of failed hosts between php processes. This will ensure we remove the overhead of the connection timeout on every first request to the API if another thread already experienced a timeout.

**Comment by jjin-gfm** [comment]
@rayrutjes, it is causing high load on our servers whenever this happens.

Was informed that the newest version of the client should have some improvements, so we'll try that Monday!
