### ISSUE TITLE
Search with facets Disjunctive & Conjunctive at the same time

### ISSUE THREAD

**Issue by kokliKo** [algolia/algoliasearch-client-php#188]
I haven't found a way to make a search which contains some disjunctive facets and some conjunctive facets, using `searchDisjunctiveFacets`.
Is it possible to do that?

There is a way to make an OR between facets by using `filters`, but is it going to retrieve the values for the facets that are not passed?

**Comment by maxiloc** [comment]
You can now do:

```
$index->search('query', ['facets' => ['facet1'], 'disjunctiveFacets' => ['facet2']])
```

You can not use `filters` with refinements that are disjunctive facets.
For those one you need to use `facetFilters`

**Comment by kokliKo** [comment]
Boom! Thanks @maxiloc

**Comment by Briones** [comment]
It's possible to use facetFilters to create an OR instead of an AND?

for example: 

`$index->search('query', ['facetFilter' => ['category:Phone', 'category:Computers'], 'disjunctiveFacets' => ['category']])`

In order to get the Categories Phone or Computers and still get the disjunctive facets category. I'm trying that but when I add the second facetFilter I don't get any results
