### ISSUE TITLE
why is there not a getFacetStats ?

### ISSUE THREAD

**Issue by wizamohamed** [algolia/algoliasearch-client-php#350]
Hello there, 

My problem is that when a user specifies a numeric filter (lets say a price) the price facet_stats contains data only related to the results, but i want to keep getting the max and min prices of all my produts (not just the result subset). 

I noticed that in other clients you provide a getFacetStats(facetName) to get the global stats of that facet, is that possible with numeric filters too ? why is this function absent on this client ? 

Thank you

**Comment by julienbourdeau** [comment]
Hi,

I checked and I can only find this function in JavaScript. I think it wasn't added because it seems pretty specific to display filter boundaries that are not the boundaries of your current results.

You can still achieve it by making a separate call with an empty query string and removing other filters. It's what `getFacetStats(facetName)` is doing internally.

Would that work for you? Also, I have to ask, have you considered doing frontend search with [InstantSearch](https://community.algolia.com/instantsearch.js/)?

**Comment by wizamohamed** [comment]
Yes, it's actually what I did in my case.
The InstantSearch client seems interesting, i will probably give it a try.
Thank you

**Comment by mnapoli** [comment]
Hi, personally I think it would be great if the PHP client was on par with the Javascript one. We reimplemented that in our application but why not distribute that part of this package? Cheers.
