### ISSUE TITLE
Algolia Timed Out Exception

### ISSUE THREAD

**Issue by ukabthebest** [algolia/algoliasearch-client-php#366]
Implementing Algolia Search in Laravel 5.5
When internet connectivity is disrupted or limited, Algolia throws a Timed Out Exception when ever handling models with searchable traits. This causes the application to crash even if a search is not being performed.
How should one catch this exception and handle it? Obviously it would be tedious to handle it everywhere in the project where a Model uses "searchable" trait.

**Comment by julienbourdeau** [comment]
You shouldn't get a timeout exception unless you are indexing or searching. I assume this happens when you are creating/updating/deleting models.

By default, these operations will dispatch a call to Algolia so this is the expected behavior to fail if you could index. 
The best way to handle that would be to activate the queue. It would prevent your app from breaking because it will call algolia "asynchronously". If it fails, it will even retry
https://laravel.com/docs/5.7/scout#queueing

If you have this issue while developing, typically using your mobile connection, turning off Algolia by using the null engine is the way to go.
