### ISSUE TITLE
Shouldn't 'generateSecuredAPIKey' be static ?

### ISSUE THREAD

**Issue by Jerskouille** [algolia/algoliasearch-client-php#40]
We don't need a client instance to generate a key so it should probably be on the root object, shoudn't it?

**Comment by vvo** [comment]
randolmly stumbled on this and yes this should be static.

**Comment by Taluu** [comment]
Hello, this is a nice BC Break :{

**Comment by maxiloc** [comment]
@Taluu Can you explain why ?

Because:

```
class A
{
        public static function test()
        {
                echo "test";
        }
}

$a = new A();
$a->test();
```

is working fine

**Comment by Taluu** [comment]
`Error: Using $this when not in object context`, because we were using `$client->generateSecuredApiKey()` :}

It's simple as that. Changing a method signature (Even just changing a simple non static method to a static one) is a bc break anyway...

The issue makes sense though, but adding a warning could have been nice in the changelog though

**Comment by maxiloc** [comment]
Not sure to follow, $client->generateSecuredApiKey() should not fail even with the new version.
But I agree with you we could have handle this change better.

**Comment by Taluu** [comment]
It does not, it just issues a warning (which makes some of our tests fails).

On strict standards, PHP does not like it if you call a static method like a normal method (php7 I guess).

**Comment by maxiloc** [comment]
ah yes indeed, that would explain.
Thanks for reporting this, we'll try to be extra careful with this kind of change in the future
