### ISSUE TITLE
Multi level OR / AND in security tags

### ISSUE THREAD

**Issue by sylfabre** [algolia/algoliasearch-client-php#51]
Let's say I want to do this config for my security tags
(public AND (catalogue_1 OR catalogue_2)) OR plateform_1

which is in PHP
`array(
   array('public', array('catalogue_1', 'catalogue_2')),
   'plateform_1'
);`

Doing so leads to this error
Array to string conversion in vendor/algolia/algoliasearch-client-php/src/AlgoliaSearch/Client.php:376

**Comment by sylfabre** [comment]
Actually I'm not so sure that my PHP translation is correct: as everything is between parenthesis, the AND seems to turn into OR.
Is it possible to have this sub-level AND?

**Comment by Nagriar** [comment]
Hi @sylfabre,

Sorry for the late reply, I missed your issue.

For performance reason, it's not possible to have ```x OR (y and z)``` we only allow ```x AND (y or z)``` that's why the PHP code doesn't handle the third level of array.

I recommend to compute the condition ```public AND (catalogue_1 OR catalogue_2)``` at indexing time. It's really better for the performance at query time. ;)

**Comment by sylfabre** [comment]
@Nagriar I've updated my code, thanks !
