### ISSUE TITLE
browseObjects Problems

### ISSUE THREAD

**Issue by fvoverscan** [algolia/algoliasearch-client-php#511]
HI,

In algolia docs :
https://www.algolia.com/doc/api-reference/api-methods/browse/?language=php

Method signature is not the same as the code example.
```
$index->browseObjects([
  // All the following parameters are optional
  'query' => query,
  // + any browseParameters
  // + any requestOptions
])
```

But on code example there is :
```
$query = ''; // Empty query will match all records
foreach ($index->browseObjects($query, ['filters' => 'i<42']) as $hit) {
  var_dump($hit);
}
```
The code example doesn't seems to work and throw an error :
`Unsupported operand types` on `AbstractAlgoliaIterator`

Others questions 
`hitPerPage` seems blocked at 1000, i can't retrieve more then 1000 hits.. is it the normal behavior ?
Why distinct is forced to false (i need to distinct hits) ?

I use the lastest stable version of the client.

Thanks

**Comment by julienbourdeau** [comment]
Hi @fvoverscan,

Indeed the example was wrong, I just open a PR on our doc, it should be live soon.

```php
$args = ['query' => $query, 'filters' => 'i<42'];

foreach ($index->browseObjects($args) as $hit) {
  var_dump($hit);
}
```

The browse methods returns an iterator. First, it will grab the first 1,000 results, then when you need to read the 1,001th, it will automatically call back Algolia to get a new batch of 1,000 results.

Distinct is false, because browse is typically used to export your index content, so it's best to not dedup.

Can you let me more about what you're trying to achieve?
