### ISSUE TITLE
Global state

### ISSUE THREAD

**Issue by ostrolucky** [algolia/algoliasearch-client-php#592]
- Algolia Client Version: 2.4.0
- Language Version: 7.3.11

### Description
I wasn't sure if I should create issue here or in composer show algolia/algoliasearch-client-php, but here it goes:

It's hard to adjust some things in traditional Symfony application, because on several critical places you rely on global static calls too much.

Some examples:

How do I inject monolog logger?
How do I inject Http Client?

Can't, I have to call `Algolia::setLogger()`, `Algolia::setHttpClient()` respectively. I would expect I can inject these directly, but can't due to these calls:

https://github.com/algolia/algoliasearch-client-php/blob/602748161cecbf9d329379a9949d63e1dc683852/src/RetryStrategy/ApiWrapper.php#L255 https://github.com/algolia/algoliasearch-client-php/blob/602748161cecbf9d329379a9949d63e1dc683852/src/SearchClient.php#L70

**Comment by ostrolucky** [comment]
Actually I see now http client is injectable into ApiWrapper, but Logger still isn't.

> Could you explain what you're trying to achieve and why?

Inject logger. For both HTTP and CLI. For logging and troubleshooting purposes.

> Why do you need to inject the Http Client, and not set it in the Algolia class 

Services are defined in DI config. Where would I put these `set(Logger|HttpClient)` calls so I can pull these services out from DI container and specify them in this getter? And how would I do it with single setting for both HTTP and CLI? Not even mentioning that this further complicates things in cases when user might need different instances of algolia services - but I don't need that right now.

My suggestions: 
- Make Logger injectable into ApiWrapper constructor as optional argument, or remove the logger concept - these days this is handled by middlewares in http clients, you don't log any useful additional information anyway
- In case you want to keep logger, still use these static getters, but only as fallback - this way it's backwards compatible
```php
private function log($level, $message, array $context = array())
{
    ($this->logger ?? Algolia::getLogger())->log($level, 'Algolia API client: '.$message, $context);
}
```

**Comment by julienbourdeau** [comment]
I think at some point the Logger was used in different places in the lib. In the send it's only in the ApiWrapper, so it makes sense to add it to the constructor. Mostly because I like seeing in the constructor that is used in the class.

I don't want to remove the logger concepts, it helps a lot on support. This lib is used in a wide variety of projects like WordPress for instance. See how we maintain compat' with PHP 5.3, I doubt injecting a middleware to an HTTP client will be an easy task.

I don't think it's an issue to inject yours today with Symfony but I can't recall how I used to do it. Maybe it was with [static factories](https://symfony.com/doc/current/service_container/factories.html) or maybe with [Service Definition](https://symfony.com/doc/current/service_container/definitions.html).

I'm trying to see if there is an easier way, like ServiceProvider in Laravel or initializers in Ruby On Rails, but I can't find it 🤷‍♂ 

> user might need different instances of algolia services

Different instances of Algolia service is fine. The issue would be different in HttpClient and/or different Loggers. I thought about it when I designed it, but I really don't think it will ever happen. I can't find a good reason why you'd do that.

Anyway, a lot of talking to say that I'll make the logger injectable anyway 😄 haha
