### ISSUE TITLE
Error when trying to export using browseObjects

### ISSUE THREAD

**Issue by onassar** [algolia/algoliasearch-client-php#629]
- Algolia Client Version: `2.5.1`
- Language Version: `7.2.24-0ubuntu0.18.04.6`

### Description
When trying to use this article (https://www.algolia.com/doc/guides/sending-and-managing-data/manage-your-indices/how-to/exporting-index-data-to-a-file/?language=php) to export an index, I run into the following errors (partial stack trace): https://i.imgur.com/8tBRgA9.png

### Steps To Reproduce
Try to use the `browserObjects` method against an index.

### Sidenote
I believe your documentation on this page (https://www.algolia.com/doc/guides/sending-and-managing-data/manage-your-indices/how-to/exporting-index-data-to-a-file/?language=php) may be out of date: it's recommending we use a `browse` method, which as far as I can tell, is no longer part of the SDK (maybe I'm wrong).

**Comment by onassar** [comment]
Anyone from Algolia able to look into this?

**Comment by chloelbn** [comment]
Hi @onassar ! Thank you for letting us know about this problem. Indeed the right way to achieve what you're aiming for would be to use `$index->browseObjects()` instead of `$index->browse('')`. A PR has been submitted to fix this page of our documentation. I'm closing this issue, feel free to reopen it if you're still experiencing problems.
