### ISSUE TITLE
Implement the new API client spec

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-client-php#75]
APPID-1.algolianet.com, APPID-2.algolianet.com and APPID-3.algolianet.com need to be in random order

**Comment by rayrutjes** [comment]
Actually classes are directly reading the public $readHostsArray and $writeHostsArray properties which means we are going to need to refactor the code a bit.
Also we should take care to not break the ClientContext constructor signature.

**Comment by maxiloc** [comment]
In the latest version we abstracted it to handle places. I think we just need to modify these two functions https://github.com/algolia/algoliasearch-client-php/blob/master/src/AlgoliaSearch/ClientContext.php#L131-L161

**Comment by rayrutjes** [comment]
I will soon make a PR. It is not as simple as to simple change the suggested methods because other classes directly accesses the public properties which in turn are initialised at construction. This means that once initialized, every call with the same context will have the same hosts set.

It all comes down to: are we ok dealing with the same hosts per ClientContext, or should we make the array random for every single api call. 

The only way to ensure we do not introduce backward compatibility issues is to make use of the magic __get method, and make the ${read|write}HostsArray private.

**Comment by maxiloc** [comment]
Ah yes nice catch

**Comment by rayrutjes** [comment]
Actually, after checking, we should ensure that every call goes to the same set of hosts, so the solution was simple finally!

**Comment by redox** [comment]
> It all comes down to: are we ok dealing with the same hosts per ClientContext, or should we make the array random for every single api call.

We absolutely need to use the same host across api calls, to leverage the keep-alive & to send all indexing job to a single machine in a row.

**Comment by rayrutjes** [comment]
@redox that is what has been done in fine. Just trying to get the security tests pass correctly right now.

**Comment by rayrutjes** [comment]
By the way, do you have a clue of why these security tests tend to fail randomly?

**Comment by rayrutjes** [comment]
@maxiloc PR #77 is ready for review.
